spring.application.name=api-gateway
server.port=8080

# Cấu hình chuỗi bí mật JWT (phải GIỐNG HỆT bên auth-service)
jwt.secret=CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te

# Route 1: Chuyển hướng các request /auth/** tới Auth Service (Cổng 8081)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route 2: Chuyển hướng các request /courses/** tới Course Service (Cổng 8082)
spring.cloud.gateway.routes[1].id=course-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/courses/**

# Route 3: Chuyển hướng các request /registrations/** tới Registration Service (Cổng 8083)
spring.cloud.gateway.routes[2].id=registration-service
spring.cloud.gateway.routes[2].uri=http://localhost:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/registrations/**